# Generated by Django 4.0.4 on 2022-05-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
