# Generated by Django 4.0.4 on 2022-05-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0009_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
