# Generated by Django 4.0.4 on 2022-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_owner',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
