# Generated by Django 4.0.4 on 2022-06-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chat_message_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_owner',
        ),
    ]
