# Generated by Django 4.0.4 on 2022-06-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
