# Generated by Django 4.0.4 on 2022-06-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_alter_chatgroupsname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroupsname',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото группы'),
        ),
    ]
