# Generated by Django 4.0.4 on 2022-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_chatingroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderChatGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Имя папки')),
                ('group', models.ManyToManyField(related_name='group_folder', to='chat_app.chatgroupsname')),
            ],
        ),
    ]
