# Generated by Django 4.0.4 on 2022-06-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0013_folderchatgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderchatgroups',
            name='group',
        ),
        migrations.AlterField(
            model_name='chatgroupsname',
            name='name',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='folderchatgroups',
            name='name',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Имя папки'),
        ),
        migrations.CreateModel(
            name='FolderGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_group', to='chat_app.folderchatgroups')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_group', to='chat_app.chatgroupsname')),
            ],
        ),
    ]
