# Generated by Django 4.0.4 on 2022-06-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0014_remove_folderchatgroups_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderchatgroups',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users_folder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
