# Generated by Django 4.0.4 on 2022-06-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0015_folderchatgroups_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldergroups',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chat_app.folderchatgroups'),
        ),
    ]
