# Generated by Django 4.0.4 on 2022-06-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0018_rename_name_chatgroupsname_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldergroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_group', to='chat_app.chatgroupsname', unique=True),
        ),
    ]
