# Generated by Django 4.0.4 on 2022-06-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0019_alter_foldergroups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldergroups',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder_group', to='chat_app.chatgroupsname'),
        ),
    ]
