# Generated by Django 4.0.4 on 2022-05-17 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_alter_post_tag'),
        ('hashtag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtag_app.tags')),
            ],
        ),
    ]
