# Generated by Django 4.0.4 on 2022-06-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag_app', '0015_alter_posttags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='hashtag_app.tags'),
        ),
    ]
