# Generated by Django 4.0.4 on 2022-05-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0008_comments_user_post_user_alter_profile_user_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'title', 'verbose_name_plural': 'title'},
        ),
    ]
