# Generated by Django 4.0.4 on 2022-05-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
