# Generated by Django 4.0.4 on 2022-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0014_alter_post_image_alter_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
