# Generated by Django 4.0.4 on 2022-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0016_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.IntegerField(),
        ),
    ]
