# Generated by Django 4.0.4 on 2022-05-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='text_comment',
        ),
    ]
