# Generated by Django 4.0.4 on 2022-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
