# Generated by Django 4.0.4 on 2022-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_friends_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
