# Generated by Django 4.0.4 on 2022-05-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_delete_like'),
        ('like_app', '0002_likecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='posts_app.post'),
        ),
    ]
