# Generated by Django 4.0.4 on 2022-05-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0006_remove_comments_like'),
        ('like_app', '0003_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comment_user', to='comments_app.comments'),
        ),
    ]
